# Generated by Django 5.1.6 on 2026-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending scheduling'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('service_mode', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Captive portal / hotspot')], default='pppoe', max_length=10)),
                ('address', models.TextField(blank=True, default='')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('pppoe_username', models.CharField(blank=True, default='', max_length=100)),
                ('pppoe_password', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Phone call'), ('web', 'Web form'), ('referral', 'Referral'), ('manual', 'Manually added')], default='manual', max_length=20)),
                ('intent', models.CharField(choices=[('unknown', 'Unknown'), ('home', 'Home / single-site'), ('cluster', 'Cluster (hotel, hostel, lodge)'), ('technical', 'Technical question (existing customer)'), ('other', 'Other')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('quoted', 'Quoted'), ('paid', 'Paid'), ('installed', 'Installed'), ('lost', 'Lost')], default='new', max_length=20)),
                ('quoted_amount_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
