# Generated by Django 5.1.6 on 2026-04-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('billing', '0005_historicalpayment_installation_order_and_more'),
        ('leads', '0001_initial'),
        ('plans', '0004_serviceplan_routers'),
        ('routers', '0008_historicalrouter_offline_strikes_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationorder',
            name='assigned_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_installations', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_orders', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_orders', to='accounts.reseller'),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_orders', to='routers.router'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_lead', to='accounts.subscriber'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='plans.serviceplan'),
        ),
        migrations.AddField(
            model_name='lead',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.reseller'),
        ),
        migrations.AddField(
            model_name='installationorder',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_orders', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['reseller', 'status'], name='leads_lead_reselle_9aeab9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['reseller', 'phone'], name='leads_lead_reselle_051613_idx'),
        ),
        migrations.AddIndex(
            model_name='installationorder',
            index=models.Index(fields=['reseller', 'status'], name='leads_insta_reselle_e12725_idx'),
        ),
    ]
