# Generated by Django 5.1.6 on 2026-05-01 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='click_id',
            field=models.CharField(blank=True, default='', help_text='TikTok ttclid / Meta fbclid / Google gclid', max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='landing_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='lead',
            name='intent',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('home', 'Home / home-office'), ('sme', 'SME (hotel, small factory, business)'), ('cluster', 'Building hotspot (hostel, lodge, 50+ residents)'), ('technical', 'Technical question (existing customer)'), ('other', 'Other')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.reseller'),
        ),
    ]
