# Generated by Django 5.1.6 on 2026-05-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_click_id_lead_landing_url_lead_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home', 'Home / home-office'), ('sme', 'SME (hotel, factory, business)'), ('cluster', 'Building hotspot (50+ residents)')], db_index=True, help_text='Maps to Lead.intent for routing.', max_length=10)),
                ('name', models.CharField(help_text='Display name on the public card, e.g. "Home Internet".', max_length=100)),
                ('tagline', models.CharField(blank=True, default='', help_text='Short pitch under the name, e.g. "Reliable WiFi for your home".', max_length=200)),
                ('upfront_label', models.CharField(default='Installation', help_text='Label for the upfront fee, e.g. "Installation" or "Account opening".', max_length=50)),
                ('upfront_price_ngn', models.DecimalField(decimal_places=2, help_text='Sticker / "from" price for the upfront fee (NGN).', max_digits=12)),
                ('upfront_discount_price_ngn', models.DecimalField(blank=True, decimal_places=2, help_text='Optional promo price. When set, the sticker price is shown struck-through and a % off badge appears.', max_digits=12, null=True)),
                ('monthly_price_ngn', models.DecimalField(decimal_places=2, help_text='Recurring monthly subscription price (NGN).', max_digits=12)),
                ('features', models.TextField(blank=True, default='', help_text='One feature per line. Rendered as a checkmark list on the card.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive plans are hidden from the public site.')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers render first on the landing page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'category', 'pk'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='leads_prici_is_acti_2695bc_idx')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='chosen_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.pricingplan'),
        ),
    ]
