# Generated by Django 5.1.6 on 2026-05-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_seed_pricing_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='best_for',
            field=models.CharField(blank=True, default='', help_text='Short "best for" hint shown on the card, e.g. "lodges · hostels · malls".', max_length=120),
        ),
    ]
