# Generated by Django 5.1.6 on 2026-03-07 16:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('paystack_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('free', 'Free Plan')], default='card', max_length=20)),
                ('commission_pct_applied', models.DecimalField(decimal_places=2, default=0, help_text='Commission % applied at time of this transaction', max_digits=5)),
                ('fee_bearer_applied', models.CharField(default='subaccount', max_length=20)),
                ('platform_amount_ngn', models.DecimalField(decimal_places=2, default=0, help_text="Platform's share of this payment", max_digits=10)),
                ('reseller_amount_ngn', models.DecimalField(decimal_places=2, default=0, help_text="Reseller's share of this payment", max_digits=10)),
                ('gateway_fee_ngn', models.DecimalField(decimal_places=2, default=0, help_text='Paystack transaction fee', max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plans.serviceplan')),
                ('reseller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.reseller')),
                ('subscriber', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.subscriber')),
            ],
            options={
                'verbose_name': 'historical payment',
                'verbose_name_plural': 'historical payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_reference', models.CharField(blank=True, default='', max_length=200, unique=True)),
                ('paystack_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('free', 'Free Plan')], default='card', max_length=20)),
                ('commission_pct_applied', models.DecimalField(decimal_places=2, default=0, help_text='Commission % applied at time of this transaction', max_digits=5)),
                ('fee_bearer_applied', models.CharField(default='subaccount', max_length=20)),
                ('platform_amount_ngn', models.DecimalField(decimal_places=2, default=0, help_text="Platform's share of this payment", max_digits=10)),
                ('reseller_amount_ngn', models.DecimalField(decimal_places=2, default=0, help_text="Reseller's share of this payment", max_digits=10)),
                ('gateway_fee_ngn', models.DecimalField(decimal_places=2, default=0, help_text='Paystack transaction fee', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='plans.serviceplan')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.reseller')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
