# Generated by Django 5.1.6 on 2026-03-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('plan', 'Plan Purchase'), ('signup_fee', 'Account Creation Fee')], default='plan', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('plan', 'Plan Purchase'), ('signup_fee', 'Account Creation Fee')], default='plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='plans.serviceplan'),
        ),
    ]
