# Generated by Django 5.1.6 on 2026-04-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicalsubscriber_auto_renew_enabled_and_more'),
        ('billing', '0002_add_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('free', 'Free Plan'), ('wallet', 'Wallet Balance'), ('refill_card', 'Refill Card')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('plan', 'Plan Purchase'), ('signup_fee', 'Account Creation Fee'), ('wallet_topup', 'Wallet Top-up'), ('auto_renewal', 'Auto Renewal')], default='plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('free', 'Free Plan'), ('wallet', 'Wallet Balance'), ('refill_card', 'Refill Card')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('plan', 'Plan Purchase'), ('signup_fee', 'Account Creation Fee'), ('wallet_topup', 'Wallet Top-up'), ('auto_renewal', 'Auto Renewal')], default='plan', max_length=20),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('refill_card', 'Refill Card'), ('paystack_topup', 'Paystack Top-up'), ('plan_purchase', 'Plan Purchase'), ('plan_renewal', 'Plan Auto-Renewal'), ('reseller_credit', 'Reseller Credit'), ('reseller_debit', 'Reseller Debit'), ('refund', 'Refund')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
