# Generated by Django 5.1.6 on 2026-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_historicalpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='reseller_amount_ngn',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Partner's share of this payment", max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reseller_amount_ngn',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Partner's share of this payment", max_digits=10),
        ),
    ]
