# Generated by Django 5.1.6 on 2026-04-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('billing', '0004_alter_historicalpayment_reseller_amount_ngn_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='installation_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.installationorder'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='payment',
            name='installation_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='leads.installationorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('plan', 'Plan Purchase'), ('signup_fee', 'Account Creation Fee'), ('wallet_topup', 'Wallet Top-up'), ('auto_renewal', 'Auto Renewal'), ('lead_install', 'Lead install payment')], default='plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('plan', 'Plan Purchase'), ('signup_fee', 'Account Creation Fee'), ('wallet_topup', 'Wallet Top-up'), ('auto_renewal', 'Auto Renewal'), ('lead_install', 'Lead install payment')], default='plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.subscriber'),
        ),
    ]
