from django.db import models
from simple_history.models import HistoricalRecords


class VoucherBatch(models.Model):
    """A batch of prepaid voucher cards generated by a reseller."""
    VALIDITY_TYPE_CHOICES = [
        ('from_activation', 'From First Activation'),
        ('fixed_date', 'Fixed Expiry Date'),
    ]
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('disabled', 'Disabled'),
    ]

    reseller = models.ForeignKey(
        'accounts.Reseller', on_delete=models.CASCADE, related_name='voucher_batches'
    )
    plan = models.ForeignKey(
        'plans.ServicePlan', on_delete=models.CASCADE, related_name='voucher_batches'
    )
    name = models.CharField(max_length=200, help_text="Batch label, e.g. 'January 2GB batch'")
    quantity = models.PositiveIntegerField()
    pin_length = models.PositiveIntegerField(default=8)
    prefix = models.CharField(
        max_length=6, blank=True, default='',
        help_text="Optional prefix for PINs, e.g. 'SW'. Prevents collision with phone numbers."
    )
    validity_type = models.CharField(max_length=20, choices=VALIDITY_TYPE_CHOICES, default='from_activation')
    validity_days = models.PositiveIntegerField(
        null=True, blank=True,
        help_text="Days from first activation (used when validity_type=from_activation)"
    )
    validity_fixed_date = models.DateTimeField(
        null=True, blank=True,
        help_text="Absolute expiry date (used when validity_type=fixed_date)"
    )
    simultaneous_use = models.PositiveIntegerField(default=1)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')
    created_at = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.name} ({self.quantity} cards)'

    @property
    def vouchers_used(self):
        return self.vouchers.exclude(status='unused').count()

    @property
    def vouchers_available(self):
        return self.vouchers.filter(status='unused').count()


class Voucher(models.Model):
    """An individual prepaid voucher card."""
    STATUS_CHOICES = [
        ('unused', 'Unused'),
        ('active', 'Active'),
        ('expired', 'Expired'),
        ('disabled', 'Disabled'),
    ]

    batch = models.ForeignKey(VoucherBatch, on_delete=models.CASCADE, related_name='vouchers')
    reseller = models.ForeignKey(
        'accounts.Reseller', on_delete=models.CASCADE, related_name='vouchers'
    )
    plan = models.ForeignKey(
        'plans.ServicePlan', on_delete=models.CASCADE, related_name='vouchers'
    )
    pin = models.CharField(max_length=20, db_index=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='unused')
    subscriber = models.ForeignKey(
        'accounts.Subscriber', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='vouchers'
    )
    activated_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()

    class Meta:
        unique_together = ['reseller', 'pin']
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.pin} ({self.status})'


class RefillCardBatch(models.Model):
    """A batch of refill cards for topping up subscriber wallets."""
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('disabled', 'Disabled'),
    ]

    reseller = models.ForeignKey(
        'accounts.Reseller', on_delete=models.CASCADE, related_name='refill_batches'
    )
    name = models.CharField(max_length=200)
    quantity = models.PositiveIntegerField()
    value_ngn = models.DecimalField(max_digits=10, decimal_places=2)
    pin_length = models.PositiveIntegerField(default=10)
    prefix = models.CharField(max_length=6, blank=True, default='')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.name} (₦{self.value_ngn} x {self.quantity})'

    @property
    def cards_used(self):
        return self.refill_cards.filter(status='used').count()

    @property
    def cards_available(self):
        return self.refill_cards.filter(status='unused').count()


class RefillCard(models.Model):
    """An individual refill card that adds balance to a subscriber's wallet."""
    STATUS_CHOICES = [
        ('unused', 'Unused'),
        ('used', 'Used'),
        ('disabled', 'Disabled'),
    ]

    batch = models.ForeignKey(RefillCardBatch, on_delete=models.CASCADE, related_name='refill_cards')
    reseller = models.ForeignKey(
        'accounts.Reseller', on_delete=models.CASCADE, related_name='refill_cards'
    )
    pin = models.CharField(max_length=20, db_index=True)
    value_ngn = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='unused')
    redeemed_by = models.ForeignKey(
        'accounts.Subscriber', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='redeemed_refill_cards'
    )
    redeemed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['reseller', 'pin']
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.pin} — ₦{self.value_ngn} ({self.status})'
