# Generated by Django 5.1.6 on 2026-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice'), ('web', 'Web chat')], max_length=10)),
                ('external_thread_id', models.CharField(db_index=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_display_name', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(choices=[('open', 'Open'), ('pending_human', 'Pending human action'), ('ai_drafted', 'AI drafted reply awaiting approval'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('body', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('external_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sender_phone', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('human_staff', 'Human staff'), ('ai_sales', 'AI sales'), ('ai_support', 'AI support'), ('ai_field', 'AI field supervisor'), ('system', 'System')], default='customer', max_length=20)),
                ('delivery_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_error', models.TextField(blank=True, default='')),
                ('agent_run_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
