# Generated by Django 5.1.6 on 2026-04-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('conversations', '0001_initial'),
        ('leads', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.reseller'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.subscriber'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to='staff.staffmember'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['reseller', 'state'], name='conversatio_reselle_92ff2f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['reseller', 'channel'], name='conversatio_reselle_8f4658_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('reseller', 'channel', 'external_thread_id')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_message_id'], name='conversatio_externa_c7658c_idx'),
        ),
    ]
