# Generated by Django 5.1.6 on 2026-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('conversations', '0003_message_is_draft'),
        ('leads', '0002_initial'),
        ('staff', '0002_staffmember_can_log_in_staffmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('customer', 'Customer'), ('tech', 'Field tech')], db_index=True, default='customer', help_text='customer = end-user thread; tech = field-tech dispatch thread.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['reseller', 'kind', 'state'], name='conversatio_reselle_80db68_idx'),
        ),
    ]
