# Generated by Django 5.1.6 on 2026-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='diagnostic_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
