# Generated by Django 5.1.6 on 2026-03-07 16:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRouter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending_provision', 'Pending Provision'), ('provisioned', 'Provisioned'), ('online', 'Online'), ('offline', 'Offline'), ('failed', 'Failed')], default='available', max_length=20)),
                ('location_name', models.CharField(blank=True, default='', max_length=200)),
                ('wg_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('wg_tunnel_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nas_secret', models.CharField(blank=True, default='', max_length=255)),
                ('api_username', models.CharField(blank=True, default='sabiwifi', max_length=100)),
                ('api_password', models.CharField(blank=True, default='', help_text='Encrypted at rest', max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('provision_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.reseller')),
            ],
            options={
                'verbose_name': 'historical router',
                'verbose_name_plural': 'historical routers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending_provision', 'Pending Provision'), ('provisioned', 'Provisioned'), ('online', 'Online'), ('offline', 'Offline'), ('failed', 'Failed')], default='available', max_length=20)),
                ('location_name', models.CharField(blank=True, default='', max_length=200)),
                ('wg_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('wg_tunnel_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nas_secret', models.CharField(blank=True, default='', max_length=255)),
                ('api_username', models.CharField(blank=True, default='sabiwifi', max_length=100)),
                ('api_password', models.CharField(blank=True, default='', help_text='Encrypted at rest', max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('provision_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routers', to='accounts.reseller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
