# Generated by Django 5.1.6 on 2026-03-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrouter',
            name='wg_private_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='router',
            name='wg_private_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
