# Generated by Django 5.1.6 on 2026-03-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_add_wg_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrouter',
            name='offline_since',
            field=models.DateTimeField(blank=True, help_text='When this router last went offline. Cleared when it comes back online.', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='offline_since',
            field=models.DateTimeField(blank=True, help_text='When this router last went offline. Cleared when it comes back online.', null=True),
        ),
        migrations.CreateModel(
            name='RouterHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('online', 'Came Online'), ('offline', 'Went Offline')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='routers.router')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['router', '-created_at'], name='routers_rou_router__161bc9_idx')],
            },
        ),
    ]
