# Generated by Django 5.1.6 on 2026-03-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_add_offline_since_and_health_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrouter',
            name='device_type',
            field=models.CharField(choices=[('mikrotik', 'MikroTik'), ('openwrt', 'OpenWrt')], default='mikrotik', help_text='MikroTik uses serial number, OpenWrt uses MAC address as identifier.', max_length=10),
        ),
        migrations.AddField(
            model_name='router',
            name='device_type',
            field=models.CharField(choices=[('mikrotik', 'MikroTik'), ('openwrt', 'OpenWrt')], default='mikrotik', help_text='MikroTik uses serial number, OpenWrt uses MAC address as identifier.', max_length=10),
        ),
    ]
