# Generated by Django 5.1.6 on 2026-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0004_add_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrouter',
            name='service_mode',
            field=models.CharField(choices=[('hotspot', 'Hotspot Only'), ('pppoe', 'PPPoE Only'), ('both', 'Hotspot + PPPoE')], default='hotspot', help_text='Hotspot (captive portal), PPPoE, or both.', max_length=10),
        ),
        migrations.AddField(
            model_name='router',
            name='service_mode',
            field=models.CharField(choices=[('hotspot', 'Hotspot Only'), ('pppoe', 'PPPoE Only'), ('both', 'Hotspot + PPPoE')], default='hotspot', help_text='Hotspot (captive portal), PPPoE, or both.', max_length=10),
        ),
    ]
