# Generated by Django 5.1.6 on 2026-04-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0005_historicalrouter_service_mode_router_service_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrouter',
            name='needs_reprovision',
            field=models.BooleanField(default=False, help_text='When True, the next MikroTik heartbeat returns the provision script.'),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='wg_last_handshake',
            field=models.DateTimeField(blank=True, help_text='Last successful WireGuard handshake (tunnel-alive signal).', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='needs_reprovision',
            field=models.BooleanField(default=False, help_text='When True, the next MikroTik heartbeat returns the provision script.'),
        ),
        migrations.AddField(
            model_name='router',
            name='wg_last_handshake',
            field=models.DateTimeField(blank=True, help_text='Last successful WireGuard handshake (tunnel-alive signal).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalrouter',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat received (internet-alive signal).', null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat received (internet-alive signal).', null=True),
        ),
    ]
