# Generated by Django 5.1.6 on 2026-04-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0006_wg_handshake_and_reprovision'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrouter',
            name='board_name',
            field=models.CharField(blank=True, default='', help_text="RouterBOARD model name from /system resource (e.g. 'hAP ac²').", max_length=64),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='detected_wan',
            field=models.CharField(blank=True, default='', help_text='Which ether port currently holds the WAN DHCP lease.', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='ether_port_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of ethernet ports detected.', null=True),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='has_5ghz',
            field=models.BooleanField(blank=True, help_text='True if device has a 5GHz radio.', null=True),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='has_wifi',
            field=models.BooleanField(blank=True, help_text='True if /interface wifi exists on this device.', null=True),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='last_reprovision_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful provision delivery.', null=True),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='ros_version',
            field=models.CharField(blank=True, default='', help_text='RouterOS version reported by /system resource.', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='wifi_enabled',
            field=models.BooleanField(default=True, help_text='If False, WiFi radios are disabled at provisioning.'),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='wifi_password',
            field=models.CharField(blank=True, default='', help_text='WPA2/WPA3 password. Empty = open network.', max_length=63),
        ),
        migrations.AddField(
            model_name='historicalrouter',
            name='wifi_ssid',
            field=models.CharField(blank=True, default='', help_text='Custom SSID. Empty = use reseller branding fallback.', max_length=32),
        ),
        migrations.AddField(
            model_name='router',
            name='board_name',
            field=models.CharField(blank=True, default='', help_text="RouterBOARD model name from /system resource (e.g. 'hAP ac²').", max_length=64),
        ),
        migrations.AddField(
            model_name='router',
            name='detected_wan',
            field=models.CharField(blank=True, default='', help_text='Which ether port currently holds the WAN DHCP lease.', max_length=16),
        ),
        migrations.AddField(
            model_name='router',
            name='ether_port_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of ethernet ports detected.', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='has_5ghz',
            field=models.BooleanField(blank=True, help_text='True if device has a 5GHz radio.', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='has_wifi',
            field=models.BooleanField(blank=True, help_text='True if /interface wifi exists on this device.', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='last_reprovision_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful provision delivery.', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='ros_version',
            field=models.CharField(blank=True, default='', help_text='RouterOS version reported by /system resource.', max_length=32),
        ),
        migrations.AddField(
            model_name='router',
            name='wifi_enabled',
            field=models.BooleanField(default=True, help_text='If False, WiFi radios are disabled at provisioning.'),
        ),
        migrations.AddField(
            model_name='router',
            name='wifi_password',
            field=models.CharField(blank=True, default='', help_text='WPA2/WPA3 password. Empty = open network.', max_length=63),
        ),
        migrations.AddField(
            model_name='router',
            name='wifi_ssid',
            field=models.CharField(blank=True, default='', help_text='Custom SSID. Empty = use reseller branding fallback.', max_length=32),
        ),
    ]
