# Generated by Django 5.1.6 on 2026-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0007_historicalrouter_board_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrouter',
            name='offline_strikes',
            field=models.PositiveSmallIntegerField(default=0, help_text="Consecutive unhealthy observations. Router only flips to 'offline' after this reaches the strike threshold (hysteresis)."),
        ),
        migrations.AddField(
            model_name='router',
            name='offline_strikes',
            field=models.PositiveSmallIntegerField(default=0, help_text="Consecutive unhealthy observations. Router only flips to 'offline' after this reaches the strike threshold (hysteresis)."),
        ),
        migrations.AddField(
            model_name='routerhealthlog',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When this event was dispatched via SMS/WA (or suppressed as a blip). NULL means pending evaluation by the next check_routers run.', null=True),
        ),
        migrations.AddIndex(
            model_name='routerhealthlog',
            index=models.Index(fields=['notified_at'], name='routers_rou_notifie_e2b3fa_idx'),
        ),
    ]
