# Generated by Django 5.1.6 on 2026-05-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0008_historicalrouter_offline_strikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrouter',
            name='port_assignments',
            field=models.JSONField(blank=True, default=dict, help_text="Per-port role map: {'ether1':'wan','ether2':'pppoe',...}. Empty = legacy auto-discover-WAN-bridge-rest behaviour."),
        ),
        migrations.AddField(
            model_name='router',
            name='port_assignments',
            field=models.JSONField(blank=True, default=dict, help_text="Per-port role map: {'ether1':'wan','ether2':'pppoe',...}. Empty = legacy auto-discover-WAN-bridge-rest behaviour."),
        ),
    ]
