# Generated by Django 5.1.6 on 2026-03-07 16:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServicePlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('download_mbps', models.PositiveIntegerField(help_text='Download speed in Mbps')),
                ('upload_mbps', models.PositiveIntegerField(help_text='Upload speed in Mbps')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='Duration in days (0 if using hours)')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, help_text='Duration in hours (e.g. 0.50 for 30 min). Used when duration_days=0.', max_digits=6)),
                ('data_cap_gb', models.DecimalField(blank=True, decimal_places=2, help_text='Data cap in GB. Null = unlimited.', max_digits=10, null=True)),
                ('max_devices', models.PositiveIntegerField(default=1, help_text='Max simultaneous devices')),
                ('price_ngn', models.DecimalField(decimal_places=2, default=0, help_text='Price in Naira. 0 = free plan.', max_digits=10)),
                ('is_trial', models.BooleanField(default=False, help_text='Is this a trial/free plan?')),
                ('is_system_created', models.BooleanField(default=False, help_text='Auto-created by the system (e.g. default Free Trial). Prevents duplicate auto-creation.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available to subscribers')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.reseller')),
            ],
            options={
                'verbose_name': 'historical service plan',
                'verbose_name_plural': 'historical service plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('download_mbps', models.PositiveIntegerField(help_text='Download speed in Mbps')),
                ('upload_mbps', models.PositiveIntegerField(help_text='Upload speed in Mbps')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='Duration in days (0 if using hours)')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, help_text='Duration in hours (e.g. 0.50 for 30 min). Used when duration_days=0.', max_digits=6)),
                ('data_cap_gb', models.DecimalField(blank=True, decimal_places=2, help_text='Data cap in GB. Null = unlimited.', max_digits=10, null=True)),
                ('max_devices', models.PositiveIntegerField(default=1, help_text='Max simultaneous devices')),
                ('price_ngn', models.DecimalField(decimal_places=2, default=0, help_text='Price in Naira. 0 = free plan.', max_digits=10)),
                ('is_trial', models.BooleanField(default=False, help_text='Is this a trial/free plan?')),
                ('is_system_created', models.BooleanField(default=False, help_text='Auto-created by the system (e.g. default Free Trial). Prevents duplicate auto-creation.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available to subscribers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.reseller')),
            ],
            options={
                'ordering': ['price_ngn', 'name'],
                'unique_together': {('reseller', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubscription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.reseller')),
                ('subscriber', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.subscriber')),
                ('plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plans.serviceplan')),
            ],
            options={
                'verbose_name': 'historical subscription',
                'verbose_name_plural': 'historical subscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='plans.serviceplan')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.reseller')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.subscriber')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
