# Generated by Django 5.1.6 on 2026-04-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserviceplan',
            name='allow_auto_renew',
            field=models.BooleanField(default=True, help_text='Allow wallet-based auto-renewal on expiry'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='allow_auto_renew',
            field=models.BooleanField(default=True, help_text='Allow wallet-based auto-renewal on expiry'),
        ),
    ]
