# Generated by Django 5.1.6 on 2026-04-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicalsubscriber_auto_renew_enabled_and_more'),
        ('plans', '0002_historicalserviceplan_allow_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserviceplan',
            name='burst_download_mbps',
            field=models.PositiveIntegerField(default=0, help_text='Burst download speed in Mbps (0=disabled)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='burst_threshold_download_mbps',
            field=models.PositiveIntegerField(default=0, help_text='Burst threshold download (0=use base speed)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='burst_threshold_upload_mbps',
            field=models.PositiveIntegerField(default=0, help_text='Burst threshold upload (0=use base speed)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='burst_time_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Burst duration in seconds'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='burst_upload_mbps',
            field=models.PositiveIntegerField(default=0, help_text='Burst upload speed in Mbps (0=disabled)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='daily_download_mb',
            field=models.PositiveIntegerField(default=0, help_text='Daily download quota in MB (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='daily_fallback_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Plan activated when daily quota exceeded', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plans.serviceplan'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='daily_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Daily online time quota in minutes (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='daily_total_mb',
            field=models.PositiveIntegerField(default=0, help_text='Daily total traffic quota in MB (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='daily_upload_mb',
            field=models.PositiveIntegerField(default=0, help_text='Daily upload quota in MB (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='download_cap_gb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Download-only cap in GB. Null = unlimited.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='fallback_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Plan activated when data/time limit reached (instead of disconnect)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plans.serviceplan'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='ip_pool_name',
            field=models.CharField(blank=True, default='', help_text="MikroTik IP pool name to assign to this plan's subscribers", max_length=64),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='online_time_limit_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total online minutes allowed across sessions (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='priority',
            field=models.PositiveIntegerField(default=8, help_text='Queue priority 1(highest) to 8(lowest)'),
        ),
        migrations.AddField(
            model_name='historicalserviceplan',
            name='upload_cap_gb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upload-only cap in GB. Null = unlimited.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='burst_download_mbps',
            field=models.PositiveIntegerField(default=0, help_text='Burst download speed in Mbps (0=disabled)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='burst_threshold_download_mbps',
            field=models.PositiveIntegerField(default=0, help_text='Burst threshold download (0=use base speed)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='burst_threshold_upload_mbps',
            field=models.PositiveIntegerField(default=0, help_text='Burst threshold upload (0=use base speed)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='burst_time_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Burst duration in seconds'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='burst_upload_mbps',
            field=models.PositiveIntegerField(default=0, help_text='Burst upload speed in Mbps (0=disabled)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='daily_download_mb',
            field=models.PositiveIntegerField(default=0, help_text='Daily download quota in MB (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='daily_fallback_plan',
            field=models.ForeignKey(blank=True, help_text='Plan activated when daily quota exceeded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_fallback_for', to='plans.serviceplan'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='daily_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Daily online time quota in minutes (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='daily_total_mb',
            field=models.PositiveIntegerField(default=0, help_text='Daily total traffic quota in MB (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='daily_upload_mb',
            field=models.PositiveIntegerField(default=0, help_text='Daily upload quota in MB (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='download_cap_gb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Download-only cap in GB. Null = unlimited.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='fallback_plan',
            field=models.ForeignKey(blank=True, help_text='Plan activated when data/time limit reached (instead of disconnect)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_for', to='plans.serviceplan'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='ip_pool_name',
            field=models.CharField(blank=True, default='', help_text="MikroTik IP pool name to assign to this plan's subscribers", max_length=64),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='online_time_limit_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total online minutes allowed across sessions (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='priority',
            field=models.PositiveIntegerField(default=8, help_text='Queue priority 1(highest) to 8(lowest)'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='upload_cap_gb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upload-only cap in GB. Null = unlimited.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalserviceplan',
            name='data_cap_gb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total data cap in GB. Null = unlimited.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('limited', 'Limited')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='data_cap_gb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total data cap in GB. Null = unlimited.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('limited', 'Limited')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('online_seconds', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('quota_exceeded', models.BooleanField(default=False)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='accounts.subscriber')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='plans_daily_date_cac755_idx')],
                'unique_together': {('subscriber', 'date')},
            },
        ),
    ]
