# Generated by Django 5.1.6 on 2026-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_historicalserviceplan_burst_download_mbps_and_more'),
        ('routers', '0007_historicalrouter_board_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='routers',
            field=models.ManyToManyField(blank=True, help_text='Restrict this plan to specific routers. Leave empty to make it available on all of your routers.', related_name='plans', to='routers.router'),
        ),
    ]
