# Generated by Django 5.1.6 on 2026-04-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('field_tech', 'Field technician'), ('office_care', 'Office / customer care'), ('dispatcher', 'Dispatcher'), ('manager', 'Manager')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('coverage_areas', models.JSONField(blank=True, default=list)),
                ('shift_hours', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('current_load', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(blank=True, help_text='Null = platform-level staff (SabiWiFi itself).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='accounts.reseller')),
            ],
            options={
                'ordering': ['reseller_id', 'role', 'name'],
                'indexes': [models.Index(fields=['reseller', 'role', 'active'], name='staff_staff_reselle_d595ba_idx')],
            },
        ),
    ]
