# Generated by Django 5.1.6 on 2026-03-07 16:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReseller',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Business name', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('pending_router', 'Pending Router'), ('active', 'Active'), ('suspended', 'Suspended')], default='setup', max_length=20)),
                ('branding', models.JSONField(blank=True, default=dict, help_text='Portal branding config: portal_title, welcome_text, bg_image, logo, primary_color, template (modern/bold/minimal)')),
                ('bank_code', models.CharField(blank=True, default='', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_number', models.CharField(blank=True, default='', max_length=20)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('paystack_subaccount_code', models.CharField(blank=True, default='', max_length=100)),
                ('payment_verified', models.BooleanField(default=False)),
                ('commission_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Override platform default commission. Null = use platform default.', max_digits=5, null=True)),
                ('fee_bearer', models.CharField(blank=True, choices=[('', 'Platform Default'), ('account', 'Platform'), ('subaccount', 'Reseller')], default='', help_text='Override who bears the Paystack fee. Empty = use platform default.', max_length=20)),
                ('free_subscriber_limit', models.PositiveIntegerField(blank=True, help_text='Override default free subscriber limit. Null = use platform default.', null=True)),
                ('flutterwave_subaccount_id', models.CharField(blank=True, default='', max_length=100)),
                ('monnify_subaccount_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical reseller',
                'verbose_name_plural': 'historical resellers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business name', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('pending_router', 'Pending Router'), ('active', 'Active'), ('suspended', 'Suspended')], default='setup', max_length=20)),
                ('branding', models.JSONField(blank=True, default=dict, help_text='Portal branding config: portal_title, welcome_text, bg_image, logo, primary_color, template (modern/bold/minimal)')),
                ('bank_code', models.CharField(blank=True, default='', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_number', models.CharField(blank=True, default='', max_length=20)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('paystack_subaccount_code', models.CharField(blank=True, default='', max_length=100)),
                ('payment_verified', models.BooleanField(default=False)),
                ('commission_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Override platform default commission. Null = use platform default.', max_digits=5, null=True)),
                ('fee_bearer', models.CharField(blank=True, choices=[('', 'Platform Default'), ('account', 'Platform'), ('subaccount', 'Reseller')], default='', help_text='Override who bears the Paystack fee. Empty = use platform default.', max_length=20)),
                ('free_subscriber_limit', models.PositiveIntegerField(blank=True, help_text='Override default free subscriber limit. Null = use platform default.', null=True)),
                ('flutterwave_subaccount_id', models.CharField(blank=True, default='', max_length=100)),
                ('monnify_subaccount_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubscriber',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('pin_hash', models.CharField(blank=True, default='', max_length=255)),
                ('auth_token', models.CharField(blank=True, default='', max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.reseller')),
            ],
            options={
                'verbose_name': 'historical subscriber',
                'verbose_name_plural': 'historical subscribers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('pin_hash', models.CharField(blank=True, default='', max_length=255)),
                ('auth_token', models.CharField(blank=True, default='', max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='accounts.reseller')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reseller', 'phone')},
            },
        ),
    ]
