# Generated by Django 5.1.6 on 2026-03-21 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. NG', max_length=2, unique=True)),
                ('dial_code', models.CharField(help_text='International prefix, e.g. +234', max_length=10)),
                ('local_prefix', models.CharField(default='0', help_text='Leading digit(s) in local format, e.g. 0', max_length=5)),
                ('local_phone_length', models.IntegerField(default=11, help_text='Expected length of local-format number, e.g. 11 for Nigeria')),
                ('flag_emoji', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='historicalsubscriber',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Country determines phone format and SMS routing.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.country'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country determines phone format and SMS routing.', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.country'),
        ),
    ]
