# Generated by Django 5.1.6 on 2026-03-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreseller',
            name='signup_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalreseller',
            name='signup_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsubscriber',
            name='signup_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reseller',
            name='signup_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reseller',
            name='signup_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='signup_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
