# Generated by Django 5.1.6 on 2026-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_signup_fee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriber',
            name='auto_renew_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsubscriber',
            name='is_voucher_user',
            field=models.BooleanField(default=False, help_text='True if this subscriber was created via voucher activation.'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='auto_renew_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_voucher_user',
            field=models.BooleanField(default=False, help_text='True if this subscriber was created via voucher activation.'),
        ),
    ]
