# Generated by Django 5.1.6 on 2026-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicalsubscriber_auto_renew_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreseller',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Partner', 'verbose_name_plural': 'historical Partners'},
        ),
        migrations.AlterModelOptions(
            name='reseller',
            options={'ordering': ['-created_at'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterField(
            model_name='historicalreseller',
            name='fee_bearer',
            field=models.CharField(blank=True, choices=[('', 'Platform Default'), ('account', 'Platform'), ('subaccount', 'Partner')], default='', help_text='Override who bears the Paystack fee. Empty = use platform default.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='fee_bearer',
            field=models.CharField(blank=True, choices=[('', 'Platform Default'), ('account', 'Platform'), ('subaccount', 'Partner')], default='', help_text='Override who bears the Paystack fee. Empty = use platform default.', max_length=20),
        ),
    ]
