# Generated by Django 5.1.6 on 2026-04-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_historicalreseller_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriber',
            name='source',
            field=models.CharField(choices=[('portal', 'Self-signup (captive portal)'), ('reseller', 'Created by reseller'), ('staff', 'Created by platform staff')], default='portal', help_text='Where this account was created from.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source',
            field=models.CharField(choices=[('portal', 'Self-signup (captive portal)'), ('reseller', 'Created by reseller'), ('staff', 'Created by platform staff')], default='portal', help_text='Where this account was created from.', max_length=20),
        ),
    ]
