# Generated by Django 5.1.6 on 2026-03-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Main product image (recommended 800×800px)', upload_to='shop/products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Product gallery image', upload_to='shop/gallery/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image_url',
            field=models.URLField(blank=True, help_text='Legacy — use primary_image instead', max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Legacy — use image field instead', max_length=500),
        ),
    ]
