# Generated by Django 5.1.6 on 2026-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.CharField(max_length=128, unique=True)),
                ('shortname', models.CharField(blank=True, default='', max_length=32)),
                ('type', models.CharField(default='other', max_length=30)),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('secret', models.CharField(default='', max_length=60)),
                ('server', models.CharField(blank=True, default='', max_length=64)),
                ('community', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'NAS',
                'verbose_name_plural': 'NAS',
                'db_table': 'nas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radacct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(default='', max_length=64)),
                ('acctuniqueid', models.CharField(default='', max_length=32, unique=True)),
                ('username', models.CharField(default='', max_length=64)),
                ('realm', models.CharField(blank=True, default='', max_length=64)),
                ('nasipaddress', models.GenericIPAddressField(default='0.0.0.0')),
                ('nasportid', models.CharField(blank=True, default='', max_length=15)),
                ('nasporttype', models.CharField(blank=True, default='', max_length=32)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctinterval', models.IntegerField(blank=True, null=True)),
                ('acctsessiontime', models.IntegerField(blank=True, null=True)),
                ('acctauthentic', models.CharField(blank=True, default='', max_length=32)),
                ('connectinfo_start', models.CharField(blank=True, default='', max_length=50)),
                ('connectinfo_stop', models.CharField(blank=True, default='', max_length=50)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.CharField(blank=True, default='', max_length=50)),
                ('callingstationid', models.CharField(blank=True, default='', max_length=50)),
                ('acctterminatecause', models.CharField(blank=True, default='', max_length=32)),
                ('servicetype', models.CharField(blank=True, default='', max_length=32)),
                ('framedprotocol', models.CharField(blank=True, default='', max_length=32)),
                ('framedipaddress', models.GenericIPAddressField(default='0.0.0.0')),
            ],
            options={
                'verbose_name': 'RADIUS Accounting',
                'verbose_name_plural': 'RADIUS Accounting',
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'verbose_name': 'RADIUS Check',
                'verbose_name_plural': 'RADIUS Checks',
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'verbose_name': 'RADIUS Group Check',
                'verbose_name_plural': 'RADIUS Group Checks',
                'db_table': 'radgroupcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'verbose_name': 'RADIUS Group Reply',
                'verbose_name_plural': 'RADIUS Group Replies',
                'db_table': 'radgroupreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radpostauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('password', models.CharField(db_column='pass', default='', max_length=64)),
                ('reply', models.CharField(default='', max_length=32)),
                ('authdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RADIUS Post-Auth',
                'verbose_name_plural': 'RADIUS Post-Auth',
                'db_table': 'radpostauth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'verbose_name': 'RADIUS Reply',
                'verbose_name_plural': 'RADIUS Replies',
                'db_table': 'radreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radusergroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('groupname', models.CharField(default='', max_length=64)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'RADIUS User Group',
                'verbose_name_plural': 'RADIUS User Groups',
                'db_table': 'radusergroup',
                'managed': False,
            },
        ),
    ]
