# Generated by Django 5.1.6 on 2026-03-07 16:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_pct', models.DecimalField(decimal_places=2, default=15.0, help_text='Default platform commission percentage (e.g. 15.00)', max_digits=5)),
                ('default_fee_bearer', models.CharField(choices=[('account', 'Platform'), ('subaccount', 'Reseller')], default='subaccount', help_text='Who bears the Paystack transaction fee by default', max_length=20)),
                ('default_free_subscriber_limit', models.PositiveIntegerField(default=5, help_text='Max active subscribers on free plans before bank verification required')),
                ('paystack_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('paystack_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('termii_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('termii_sender_id', models.CharField(default='SabiWiFi', max_length=20)),
                ('platform_name', models.CharField(default='SabiWiFi', max_length=100)),
                ('platform_domain', models.CharField(default='sabiwifi.ng', max_length=255)),
                ('server_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('server_wg_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('notification_phones', models.JSONField(blank=True, default=list, help_text='JSON list of phone numbers, e.g. ["+2348012345678"]')),
                ('notify_on_new_reseller', models.BooleanField(default=True)),
                ('notify_on_router_offline', models.BooleanField(default=True)),
                ('notify_on_payment_failure', models.BooleanField(default=True)),
                ('notify_daily_summary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlatformSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('default_commission_pct', models.DecimalField(decimal_places=2, default=15.0, help_text='Default platform commission percentage (e.g. 15.00)', max_digits=5)),
                ('default_fee_bearer', models.CharField(choices=[('account', 'Platform'), ('subaccount', 'Reseller')], default='subaccount', help_text='Who bears the Paystack transaction fee by default', max_length=20)),
                ('default_free_subscriber_limit', models.PositiveIntegerField(default=5, help_text='Max active subscribers on free plans before bank verification required')),
                ('paystack_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('paystack_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('termii_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('termii_sender_id', models.CharField(default='SabiWiFi', max_length=20)),
                ('platform_name', models.CharField(default='SabiWiFi', max_length=100)),
                ('platform_domain', models.CharField(default='sabiwifi.ng', max_length=255)),
                ('server_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('server_wg_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('notification_phones', models.JSONField(blank=True, default=list, help_text='JSON list of phone numbers, e.g. ["+2348012345678"]')),
                ('notify_on_new_reseller', models.BooleanField(default=True)),
                ('notify_on_router_offline', models.BooleanField(default=True)),
                ('notify_on_payment_failure', models.BooleanField(default=True)),
                ('notify_daily_summary', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Platform Settings',
                'verbose_name_plural': 'historical Platform Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
