# Generated by Django 5.1.6 on 2026-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_panel', '0003_add_openwisp_fields_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatformsettings',
            name='default_fee_bearer',
            field=models.CharField(choices=[('account', 'Platform'), ('subaccount', 'Partner')], default='subaccount', help_text='Who bears the Paystack transaction fee by default', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalplatformsettings',
            name='openwisp_api_token',
            field=models.CharField(blank=True, default='', help_text='OpenWISP REST API bearer token (from OpenWISP admin → API tokens)', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalplatformsettings',
            name='openwisp_api_url',
            field=models.CharField(blank=True, default='', help_text='OpenWISP controller base URL, e.g. https://wisp.sabiwifi.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalplatformsettings',
            name='openwisp_pool_org_id',
            field=models.UUIDField(blank=True, help_text='UUID of the OpenWISP "pool" organization where unclaimed devices land after first boot', null=True),
        ),
        migrations.AlterField(
            model_name='historicalplatformsettings',
            name='openwisp_shared_secret',
            field=models.CharField(blank=True, default='', help_text='Shared secret baked into firmware for device auto-registration with OpenWISP', max_length=128),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='default_fee_bearer',
            field=models.CharField(choices=[('account', 'Platform'), ('subaccount', 'Partner')], default='subaccount', help_text='Who bears the Paystack transaction fee by default', max_length=20),
        ),
    ]
