# Generated by Django 5.1.6 on 2026-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_panel', '0004_alter_historicalplatformsettings_default_fee_bearer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatformsettings',
            name='notify_on_new_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalplatformsettings',
            name='notify_on_payment_failure_spike',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalplatformsettings',
            name='notify_on_reseller_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalplatformsettings',
            name='notify_on_router_recovered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalplatformsettings',
            name='operator_notification_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('both', 'Both')], default='whatsapp', help_text='Channel used to reach operator recipients', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalplatformsettings',
            name='operator_wa_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalplatformsettings',
            name='operator_wa_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_on_new_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_on_payment_failure_spike',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_on_reseller_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_on_router_recovered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='operator_notification_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('both', 'Both')], default='whatsapp', help_text='Channel used to reach operator recipients', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='operator_wa_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='operator_wa_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
