# Generated by Django 5.1.6 on 2026-05-01 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('operator_panel', '0005_historicalplatformsettings_notify_on_new_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplatformsettings',
            name='platform_reseller',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Default partner for platform-direct leads. Leave blank to land them unassigned.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.reseller'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='platform_reseller',
            field=models.ForeignKey(blank=True, help_text='Default partner for platform-direct leads. Leave blank to land them unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.reseller'),
        ),
    ]
