# Generated by Django 5.1.6 on 2026-04-08 13:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_historicalsubscriber_auto_renew_enabled_and_more'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVoucherBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="Batch label, e.g. 'January 2GB batch'", max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('pin_length', models.PositiveIntegerField(default=8)),
                ('prefix', models.CharField(blank=True, default='', help_text="Optional prefix for PINs, e.g. 'SW'. Prevents collision with phone numbers.", max_length=6)),
                ('validity_type', models.CharField(choices=[('from_activation', 'From First Activation'), ('fixed_date', 'Fixed Expiry Date')], default='from_activation', max_length=20)),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Days from first activation (used when validity_type=from_activation)', null=True)),
                ('validity_fixed_date', models.DateTimeField(blank=True, help_text='Absolute expiry date (used when validity_type=fixed_date)', null=True)),
                ('simultaneous_use', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plans.serviceplan')),
                ('reseller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.reseller')),
            ],
            options={
                'verbose_name': 'historical voucher batch',
                'verbose_name_plural': 'historical voucher batchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Batch label, e.g. 'January 2GB batch'", max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('pin_length', models.PositiveIntegerField(default=8)),
                ('prefix', models.CharField(blank=True, default='', help_text="Optional prefix for PINs, e.g. 'SW'. Prevents collision with phone numbers.", max_length=6)),
                ('validity_type', models.CharField(choices=[('from_activation', 'From First Activation'), ('fixed_date', 'Fixed Expiry Date')], default='from_activation', max_length=20)),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Days from first activation (used when validity_type=from_activation)', null=True)),
                ('validity_fixed_date', models.DateTimeField(blank=True, help_text='Absolute expiry date (used when validity_type=fixed_date)', null=True)),
                ('simultaneous_use', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_batches', to='plans.serviceplan')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_batches', to='accounts.reseller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVoucher',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pin', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='unused', max_length=10)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plans.serviceplan')),
                ('reseller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.reseller')),
                ('subscriber', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.subscriber')),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vouchers.voucherbatch')),
            ],
            options={
                'verbose_name': 'historical voucher',
                'verbose_name_plural': 'historical vouchers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='unused', max_length=10)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='plans.serviceplan')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='accounts.reseller')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='accounts.subscriber')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.voucherbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reseller', 'pin')},
            },
        ),
    ]
