# Generated by Django 5.1.6 on 2026-04-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicalsubscriber_auto_renew_enabled_and_more'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillCardBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('value_ngn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pin_length', models.PositiveIntegerField(default=10)),
                ('prefix', models.CharField(blank=True, default='', max_length=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_batches', to='accounts.reseller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefillCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(db_index=True, max_length=20)),
                ('value_ngn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('disabled', 'Disabled')], default='unused', max_length=10)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_refill_cards', to='accounts.subscriber')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_cards', to='accounts.reseller')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_cards', to='vouchers.refillcardbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reseller', 'pin')},
            },
        ),
    ]
