# Generated by Django 5.1.6 on 2026-04-24 20:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('conversations', '0005_conversation_diagnostic_state'),
        ('tickets', '0003_alter_ticket_diagnosed_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(help_text='Asterisk uniqueid / AVR UUID. Dedupes webhook events.', max_length=128, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('from_e164', models.CharField(blank=True, default='', max_length=20)),
                ('to_e164', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No answer'), ('busy', 'Busy')], default='ringing', max_length=16)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='', help_text='Full call transcript accumulated from VoiceTurn rows.')),
                ('cost_ngn', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Sum of carrier + AI costs for this call.', max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='conversations.conversation')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_calls', to='accounts.reseller')),
                ('subscriber', models.ForeignKey(blank=True, help_text='Resolved once caller-ID is matched against subscribers; nullable for new/anonymous callers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='accounts.subscriber')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_enabled', models.BooleanField(default=False, help_text='Master toggle. When False the voice droplet routes all calls for this tenant to a "temporarily unavailable" prompt.')),
                ('sip_provider_name', models.CharField(blank=True, default='', help_text='Display-only (e.g. "VoIP.ms", "MTN"). SIP creds live in sip_credentials_encrypted; empty means use platform trunk.', max_length=64)),
                ('sip_credentials_encrypted', models.TextField(blank=True, default='', help_text='Fernet-encrypted JSON: {host, username, password, port}. Access via the sip_credentials property.')),
                ('outbound_caller_id', models.CharField(blank=True, default='', help_text='E.164 number used as From: for outbound calls.', max_length=20)),
                ('tts_voice_id', models.CharField(blank=True, default='', max_length=64)),
                ('greeting_text', models.CharField(blank=True, default='', help_text='Spoken before any AI turn. Leave blank for a platform-generated greeting using reseller.name.', max_length=500)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('recording_retention_days', models.PositiveIntegerField(default=30, help_text='Days to retain recordings + transcripts. Longer = more storage cost + NDPR exposure.')),
                ('concurrent_call_cap', models.PositiveIntegerField(default=5)),
                ('enabled_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_tenant', to='accounts.reseller')),
            ],
            options={
                'verbose_name': 'Voice tenant',
            },
        ),
        migrations.CreateModel(
            name='VoiceTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound (caller speech)'), ('out', 'Outbound (AI speech)')], max_length=3)),
                ('text', models.TextField(blank=True, default='')),
                ('agent_run_id', models.BigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('cost_ngn', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='voice.voicecall')),
            ],
            options={
                'ordering': ['call', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_e164', models.CharField(help_text='The DID the caller dials, E.164 format (+23480...).', max_length=20, unique=True)),
                ('agent_role', models.CharField(choices=[('voice_customer', 'Voice — subscriber hotline'), ('voice_field', 'Voice — field-tech callback'), ('voice_reseller', 'Voice — reseller ops support'), ('voice_otp', 'Voice — OTP delivery only (no AI)')], default='voice_customer', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_routing_rules', to='accounts.reseller')),
            ],
            options={
                'indexes': [models.Index(fields=['reseller', 'is_active'], name='voice_routi_reselle_601a01_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='voicecall',
            index=models.Index(fields=['reseller', '-started_at'], name='voice_voice_reselle_4ce39e_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecall',
            index=models.Index(fields=['subscriber', '-started_at'], name='voice_voice_subscri_96161c_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecall',
            index=models.Index(fields=['status', '-started_at'], name='voice_voice_status_a1d7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceturn',
            index=models.Index(fields=['call', 'started_at'], name='voice_voice_call_id_a2766d_idx'),
        ),
    ]
