# Generated by Django 5.1.6 on 2026-04-21 18:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('conversations', '0002_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('openai_compatible', 'OpenAI-compatible (Groq/Together/Ollama)')], default='anthropic', max_length=32)),
                ('text_api_key_encrypted', models.TextField(blank=True)),
                ('text_endpoint_url', models.URLField(blank=True, help_text='Only for openai_compatible (Groq / Together / Ollama URL).')),
                ('text_model', models.CharField(blank=True, help_text='e.g. claude-sonnet-4-6, gpt-4o, gemini-2.0-flash.', max_length=128)),
                ('asr_provider', models.CharField(blank=True, choices=[('', '— none —'), ('whisper', 'Whisper'), ('deepgram', 'Deepgram'), ('google', 'Google')], default='', max_length=32)),
                ('asr_api_key_encrypted', models.TextField(blank=True)),
                ('tts_provider', models.CharField(blank=True, default='', max_length=32)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('prompt_overrides', models.JSONField(blank=True, default=dict, help_text='Active tone / FAQ / guardrails. History in AIPromptVersion.')),
                ('ai_paused_at', models.DateTimeField(blank=True, null=True)),
                ('ai_pause_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='accounts.reseller')),
            ],
            options={
                'verbose_name': 'Reseller AI config',
            },
        ),
        migrations.CreateModel(
            name='AIAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_role', models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('field', 'Field supervisor')], max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('cost_ngn', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('awaiting_approval', 'Awaiting approval'), ('human_overridden', 'Human overridden')], default='success', max_length=32)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='conversations.conversation')),
                ('human_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_runs', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='conversations.message')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='accounts.reseller')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['reseller', '-started_at'], name='ai_aiagentr_reselle_3f2dd3_idx'), models.Index(fields=['agent_role', 'status'], name='ai_aiagentr_agent_r_71d2da_idx'), models.Index(fields=['status', '-started_at'], name='ai_aiagentr_status_739387_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIPromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_role', models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('field', 'Field supervisor')], max_length=16)),
                ('body', models.TextField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to='ai.reselleraiconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['config', 'agent_role', '-created_at'], name='ai_aiprompt_config__5d1613_idx')],
            },
        ),
    ]
