# Generated by Django 5.1.6 on 2026-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentrun',
            name='agent_role',
            field=models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('field', 'Field supervisor'), ('field_inbound', 'Field inbound (tech replies)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='aipromptversion',
            name='agent_role',
            field=models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('field', 'Field supervisor'), ('field_inbound', 'Field inbound (tech replies)')], max_length=16),
        ),
    ]
