# Generated by Django 5.1.6 on 2026-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aiagentrun_agent_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentrun',
            name='agent_role',
            field=models.CharField(choices=[('customer', 'Customer (enquiry + support)'), ('sales', 'Sales (legacy)'), ('support', 'Support (legacy)'), ('field', 'Field supervisor'), ('field_inbound', 'Field inbound (tech replies)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='aipromptversion',
            name='agent_role',
            field=models.CharField(choices=[('customer', 'Customer (enquiry + support)'), ('sales', 'Sales (legacy)'), ('support', 'Support (legacy)'), ('field', 'Field supervisor'), ('field_inbound', 'Field inbound (tech replies)')], max_length=16),
        ),
    ]
