# Generated by Django 5.1.6 on 2026-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_aiagentrun_agent_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentrun',
            name='agent_role',
            field=models.CharField(choices=[('customer', 'Customer (enquiry + support)'), ('sales', 'Sales (legacy)'), ('support', 'Support (legacy)'), ('field', 'Field supervisor'), ('field_inbound', 'Field inbound (tech replies)'), ('voice_customer', 'Voice — subscriber hotline'), ('voice_field', 'Voice — field-tech callback'), ('voice_reseller', 'Voice — reseller ops support')], max_length=16),
        ),
        migrations.AlterField(
            model_name='aipromptversion',
            name='agent_role',
            field=models.CharField(choices=[('customer', 'Customer (enquiry + support)'), ('sales', 'Sales (legacy)'), ('support', 'Support (legacy)'), ('field', 'Field supervisor'), ('field_inbound', 'Field inbound (tech replies)'), ('voice_customer', 'Voice — subscriber hotline'), ('voice_field', 'Voice — field-tech callback'), ('voice_reseller', 'Voice — reseller ops support')], max_length=16),
        ),
    ]
