# Generated by Django 5.1.6 on 2026-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='diagnosed_cause',
            field=models.CharField(blank=True, choices=[('general_outage', 'General outage'), ('expired_subscription', 'Expired subscription'), ('payment_failed', 'Payment failed'), ('device_side_unknown', 'Device-side unknown'), ('pon_signal_lost', 'PON signal lost'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dispatch_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='field_ping_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_field_ping_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pending_close_action',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticket',
            name='suggested_action',
            field=models.CharField(blank=True, choices=[('no_action', 'No action'), ('customer_action', 'Customer action'), ('dispatch', 'Dispatch tech')], default='', max_length=20),
        ),
    ]
