# Generated by Django 5.1.6 on 2026-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_diagnosed_cause_ticket_dispatch_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='diagnosed_cause',
            field=models.CharField(blank=True, choices=[('general_outage', 'General outage'), ('expired_subscription', 'Expired subscription'), ('payment_failed', 'Payment failed'), ('data_cap_exhausted', 'Data cap exhausted'), ('device_side_unknown', 'Device-side unknown'), ('pon_signal_lost', 'PON signal lost'), ('other', 'Other')], default='', max_length=32),
        ),
    ]
