# Generated by Django 5.1.6 on 2026-03-22 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('alert', 'Alert'), ('promo', 'Promo'), ('marketing', 'Marketing')], max_length=15)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('both', 'WhatsApp + SMS')], default='sms', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='accounts.reseller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerAdminContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp only'), ('sms', 'SMS only'), ('both', 'WhatsApp + SMS')], default='sms', max_length=10)),
                ('recv_router_alerts', models.BooleanField(default=True)),
                ('recv_new_subscriber', models.BooleanField(default=False)),
                ('recv_payment_summary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_contacts', to='accounts.reseller')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResellerNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_plan_expiry_3d', models.BooleanField(default=True)),
                ('send_plan_expiry_1d', models.BooleanField(default=True)),
                ('send_plan_expired', models.BooleanField(default=True)),
                ('send_welcome', models.BooleanField(default=True)),
                ('subscriber_channel', models.CharField(choices=[('whatsapp', 'WhatsApp only'), ('sms', 'SMS only'), ('both', 'WhatsApp + SMS')], default='sms', max_length=10)),
                ('recv_new_subscriber', models.BooleanField(default=True)),
                ('recv_payment', models.BooleanField(default=True)),
                ('recv_router_offline', models.BooleanField(default=True)),
                ('recv_router_recovered', models.BooleanField(default=False)),
                ('reseller_channel', models.CharField(choices=[('whatsapp', 'WhatsApp only'), ('sms', 'SMS only'), ('both', 'WhatsApp + SMS')], default='sms', max_length=10)),
                ('reseller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to='accounts.reseller')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberNotificationPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactional_enabled', models.BooleanField(default=True)),
                ('transactional_channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10)),
                ('receive_alerts', models.BooleanField(default=True)),
                ('receive_promos', models.BooleanField(default=False)),
                ('receive_marketing', models.BooleanField(default=False)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to='accounts.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected')], default='disconnected', max_length=20)),
                ('wa_phone', models.CharField(blank=True, default='', max_length=30)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('reseller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_session', to='accounts.reseller')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10)),
                ('event_type', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.broadcast')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='accounts.reseller')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='accounts.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reseller', '-created_at'], name='notificatio_reselle_1fd9ac_idx'), models.Index(fields=['broadcast', 'status'], name='notificatio_broadca_4d1069_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('plan_expiry_3d', 'Plan expiring in 3 days'), ('plan_expiry_1d', 'Plan expiring tomorrow'), ('plan_expired', 'Plan expired'), ('welcome', 'Welcome message'), ('router_offline', 'Router went offline'), ('router_recovered', 'Router back online'), ('new_subscriber', 'New subscriber alert (to reseller)'), ('payment_received', 'Payment received (to reseller)')], max_length=30)),
                ('body', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='accounts.reseller')),
            ],
            options={
                'unique_together': {('reseller', 'event_type')},
            },
        ),
    ]
