# Generated by Django 5.1.6 on 2026-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_add_notification_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('plan_expiry_3d', 'Plan expiring in 3 days'), ('plan_expiry_1d', 'Plan expiring tomorrow'), ('plan_expired', 'Plan expired'), ('welcome', 'Welcome message'), ('router_offline', 'Router went offline'), ('router_recovered', 'Router back online'), ('new_subscriber', 'New subscriber alert (to partner)'), ('payment_received', 'Payment received (to partner)')], max_length=30),
        ),
    ]
