# Generated by Django 5.1.6 on 2026-04-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_historicalreseller_options_and_more'),
        ('notifications', '0002_alter_notificationtemplate_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='accounts.reseller'),
        ),
    ]
