# Generated by Django 5.1.6 on 2026-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicalsubscriber_source_subscriber_source'),
        ('notifications', '0003_alter_notificationlog_reseller'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient_phone',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('reseller', 'event_type', 'channel')},
        ),
    ]
