# Generated by Django 5.1.6 on 2026-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('plan_expiry_3d', 'Plan expiring in 3 days'), ('plan_expiry_1d', 'Plan expiring tomorrow'), ('plan_expired', 'Plan expired'), ('welcome', 'Welcome message'), ('router_offline', 'Router went offline'), ('router_recovered', 'Router back online'), ('new_subscriber', 'New subscriber alert (to partner)'), ('payment_received', 'Payment received (to partner)'), ('ticket_opened', 'Support ticket opened'), ('ticket_in_progress', 'Support ticket — tech in progress'), ('ticket_resolved', 'Support ticket resolved')], max_length=30),
        ),
    ]
